### PR TITLE
Release/4.2

### PR DESCRIPTION
**Pull request by binaryoverload**
- [ ] Completed PR - Has all features or fixes that it was meant to and isn't half done
- [x] Follows the style guide - Style guide found [here](https://github.com/FlareBot/FlareBot/blob/master/CONTRIBUTING.md)
- [x] All changes have been tested

> This PR is mostly cleanup

### CODE REVIEW

**Comment by WalshyDev** [comment]
Looks good so far, looks like there's a FlareBot folder or something added though. 
https://github.com/FlareBot/FlareBot/pull/149/files#diff-b7c42ebd007e05e15455a3595eb1420d

**Comment by binaryoverload** [comment]
Gods sakeeee, I need to add that to the gitignore

**Comment by WalshyDev** [comment]
For reference, this is the 4.2 planned list: https://gist.github.com/binaryoverload/2413faaa1e25a87391d2969e225f8620

Could we also work more on *nudge nudge* and make sure that stuff like Command and CommandManager aren't used outside the commands package. There's probably no need and just means more of a dependency on something which can be isolated. 
Also, remember to cleanup all the things Codacy caught and look through all of IntelliJ's flags for things we can improve.

**Comment by weeryan17** [comment]
[Make the current pagination system also add reactions which edit the message when the page is changed](https://trello.com/c/9PiH8Y4r/83-make-the-current-pagination-system-also-add-reactions-which-edit-the-message-when-the-page-is-changed)

**Comment by WalshyDev** [comment]
Is 4.2 in a state where we could push while I work on 2? (Apart from the merge conflicts).
Gives people an update to use and also does some much needed changes before 2 is released.

**Comment by weeryan17** [comment]
I belive it's in a stable state currently. I'd like us to have pagnation in this before merge but not having it isn't a big deal

**Pull request merged**
