### PR TITLE
Fix changelog name

### PR DESCRIPTION
**Pull request by m1guelpf**
The current changelog file is named `Changlog.md` instead of `Changelog.md`. This could be some kind of internal joke or a typo. If it's the latter, you should probably merge this.

:octocat:

### CODE REVIEW

**Comment by WalshyDev** [comment]
👀 totally knew that...
But anyway the changelog isn't actually of that significance, the actual changelog is part of the docs (which I'm doing now). The one on the repo is for v3 which is a version we never actually released and was quite a joke.
Thanks for the PR though, I'll just merge and remove the file once we get an actual changelog written and an update process done for when we do... well updates

**Comment by binaryoverload** [comment]
Beat you to it @WalshyDev tee hee hee 😉

**Comment by WalshyDev** [comment]
Shh you did the easy bit @binaryoverload

**Comment by binaryoverload** [comment]
True 😂

**Pull request merged**
