### PR TITLE
Add a self hosting tutorial

### PR DESCRIPTION
**Pull request by ArsenArsen**
- [x] Completed PR - Has all features or fixes that it was meant to and isn't half done
- [x] Follows the style guide - Style guide found [here](https://github.com/FlareBot/FlareBot/blob/master/CONTRIBUTING.md)
- [x] Your code follows the same code style as the rest of the project
- [x] Tested changes

## What is added
Self Hosting Tutorial

## What is fixed
Lack of the same

FOSS proposes anyone being able to use this software, claiming this is FOSS otherwise is wrong imho.

### CODE REVIEW

**Comment by Rayzr522** [comment]
Looks good, but it should be in a separate file from the rest of the README. 99.99999% of users aren't going to need this information, and it's pretty big and space-consuming.

**Comment by binaryoverload** [comment]
I don't believe not giving people instructions would stop this from being FOSS. Open sourcing doesn't mean that we have to actively engage with people about how it works and to give instructions, it is literally just allowing everyone to see the source code.

**Comment by binaryoverload** [comment]
Also, the self-hosting document not only is wrong but also misses bits of information required for the bot to run.

**Comment by binaryoverload** [comment]
The entire reason we don't support people who want to self-host as it will likely be hosted by people who don't want to contribute or don't want to give us suggestions and instead want to run it themselves. I firmly believe that if are not able to run FlareBot without instructions then you shouldn't be running it. I seem to believe that you defended this decision @ArsenArsen as justification to stop "script kiddies"

**Comment by ArsenArsen** [comment]
https://www.gnu.org/philosophy/free-software-for-freedom.html

What details are missing? I have no problem fixing it :)

**Comment by binaryoverload** [comment]
If you can point me to a part of that web page where we are supposed to provide support to users then I will gladly consider this. I do not see it so until I see such evidence to prove that we should, as responsible developers and main leaders of the project, provide support to users I will not condone this.

**Comment by poncethecat** [comment]
Listen, if you're going to stop users from running their own version of the bot because they "can't contribute", there is no point in it being FOSS. The whole point of FOSS is to allow people to do what they want, and run the code themselves if they feel they would like to. What if Cassandra didn't come with documentation? What about `git`?

**Comment by ArsenArsen** [comment]
Tell me a script kiddie will be capable of setting up cassandra, edit source code, set up mysql, set up a unix like system to work well, etc. Back in the day I was not kicked off of the project hosting was as easy as running the JAR, times have changed. There are lots of dependencies, which in a large part aren't easy to set up.

**Comment by binaryoverload** [comment]
@poncethecat I think you misunderstood me, I'm not stopping people from running their own version of the bot. I am saying that we will not support them with doing so.

**Comment by poncethecat** [comment]
@binaryoverload So by your philosophy, `git` and Cassandra should both come with absolutely no documentation, because if you can't figure it out yourself, you shouldn't be allowed to use it!

**Comment by binaryoverload** [comment]
That is documentation that is provided because the authors want users to actively use it. Documentation is not a required part of any free and open source software. Git and Cassandra are tools that are designed for end users. FlareBot is a piece of software that is not needed to be run by users and so is not documented or supported as such. It is unfair to compare the two.

**Comment by poncethecat** [comment]
So I ask yet again, if you don't intend it to be run by users, then why is it open-source? There's absolutely no point in it if you're going to just tell off users. For example, Gnar-bot doesn't provide direct support for self-hosting their bot, but they provide *basic* directions for self-hosting.

**Comment by binaryoverload** [comment]
We open source it for transparency and to assist other people. Open sourcing does not mean you intend other users to use it. Plus, We are not the only people taking this stance. b1nzy himself takes this sort of stance with [his bot](https://github.com/b1naryth1ef/rowboat#should-i-run-rowboat-locally). I will happily allow our readme to be updated in a similar fashion but, at the moment, a self-hosting guide will not be provided.

**Comment by poncethecat** [comment]
And then notice how on that same README, he gives instructions. on how to run it under the development section.

**Comment by ArsenArsen** [comment]
>Transparency

>Doesn't give insides on how it's ran

**Comment by binaryoverload** [comment]
"The main purpose of having the source released is to allow others to understand and audit the functionality. The code is by no means meant to be easy to setup or bootstrap, and I don't plan on supporting folks trying to run locally." This is the exact stance we will take. That is his choice to provide instructions like that, our choice is to not.

**Comment by poncethecat** [comment]
So I ask again, if you aren't even giving *general* instructions like he is, why do you open-source the code?

**Comment by binaryoverload** [comment]
Because FlareBot is not built in such a way where *general* instructions are of the same sort of caliber.

**Comment by binaryoverload** [comment]
We open source to allow people to audit functionality, take ideas, learn how to use JDA and just generally understand bot development.

**Comment by poncethecat** [comment]
This pull request's instructions *are* general. Do you think someone who only knows how to run a script is capable of editing source code, setting up databases, and compiling and running without issues? Your definition of script kiddie is apparently a system administrator.

**Comment by binaryoverload** [comment]
True

**Comment by binaryoverload** [comment]
@ArsenArsen If you PM me on discord I will go through and help you correct this PR

**Comment by binaryoverload** [comment]
After internal discussion amongst ourselves, we have decided to stick with our self-hosting non-support policy. We will not provide support for people wanting to self-host. We are not people who make this repository open source in the aim that people will use it for themselves. Moving forward, any PRs that are submitted that suggest changes to our policies that are not first discussed with a developer will be closed with no questions asked. 

This PR will be closed in due course and any conversation about it from any of the participating parties will be ignored.

**FlareBot Management Team**
@WalshyDev @binaryoverload @weeryan17

**Pull request closed without merging**
