### PR TITLE
The mighty merge

### PR DESCRIPTION
**Pull request by WalshyDev**
- [X] Completed PR - Has all features or fixes that it was meant to and isn't half done
- [X] Follows the style guide - Style guide found [here](https://github.com/FlareBot/FlareBot/blob/master/CONTRIBUTING.md)
- [X] Your code follows the same code style as the rest of the project
- [X] Is Walshy

## What is added
I'm merging data-restructure what do you think...

## What is fixed
I'm merging data-restructure what do you think...

### CODE REVIEW

**Comment by weeryan17** [comment]
yep we're going to get a flarebot error when doing this one

**Comment by binaryoverload** [comment]
@weeryan17 No we are not, it was just gradle shitting itself as usual

**Comment by weeryan17** [comment]
@binaryoverload i ment form the github channel overflowing because lots of commits

**Comment by ArsenArsen** [comment]
That's because you removed the build file.

> - [X] Is Walshy

Rejected. :^) <3

**Comment by binaryoverload** [comment]
xD

**Comment by binaryoverload** [comment]
@WalshyDev You might as well merge bc there is nothing to review xD

**Comment by ArsenArsen** [comment]
^ I agree.

**Comment by WalshyDev** [comment]
@binaryoverload well @ArsenArsen is one picky and annoying person when it comes to PRs he didn't see.

**Pull request merged**
