### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by binaryoverload**
- [x] Completed PR - Has all features or fixes that it was meant to and isn't half done

## What is fixed
Spelling of `Contributing`

### CODE REVIEW

**Comment by ArsenArsen** [comment]
While you're at it fix the badge URLs. And make the credits not checkboxes.

**Comment by binaryoverload** [comment]
Fix them? Whats wrong with them?

**Comment by ArsenArsen** [comment]
They point to the badges/shields repo instead of this one.

**Comment by binaryoverload** [comment]
ah
gotcha

**Comment by ArsenArsen** [comment]
Merging

**Pull request merged**
