### PR TITLE
Update JumboCommand.java

### PR DESCRIPTION
**Pull request by RubenRME**
Added backtick to Jumbo command per request of night. Hope I did it correctly, I'm bad. 😴

### CODE REVIEW

**Comment by weeryan17** [comment]
Why did you submit a one line pr.......

**Comment by weeryan17** [comment]
Also 10/10 job fallowing the issue template

**Comment by weeryan17** [comment]
Make a proper pr and come back. Also double check that request because well you didn't meat it

**Comment by RubenRME** [comment]
Oof, sorry for not following the format. Just did a quick edit that walshy said zNiGHTIYIaRe should make. But he couldn't /shrug

**Pull request closed without merging**
